num1=float(input("enter the number of fresh loves purchesed = "))
num2=float(input( "enter the number of old loves purchesed =  "))
print("amout of news loves  = "  ,185*num1 )
print("amout of news old = ",74*num2)
print("Total amount = ", 185*num1 +74*num2)
